export const TICKET_CREATE_REQUEST = "TICKET_CREATE_REQUEST";
export const TICKET_CREATE_SUCCESS = "TICKET_CREATE_SUCCESS";
export const TICKET_CREATE_FAIL = "TICKET_CREATE_FAIL";
export const TICKET_CREATE_RESET = "TICKET_CREATE_RESET";

export const TICKET_PAY_REQUEST = "TICKET_PAY_REQUEST";
export const TICKET_PAY_SUCCESS = "TICKET_PAY_SUCCESS";
export const TICKET_PAY_FAIL = "TICKET_PAY_FAIL";
export const TICKET_PAY_RESET = "TICKET_PAY_RESET";

export const TICKET_ANSWER_REQUEST = "TICKET_ANSWER_REQUEST";
export const TICKET_ANSWER_SUCCESS = "TICKET_ANSWER_SUCCESS";
export const TICKET_ANSWER_FAIL = "TICKET_ANSWER_FAIL";
export const TICKET_ANSWER_RESET = "TICKET_ANSWER_RESET";

export const TICKET_DETAILS_REQUEST = "TICKET_DETAILS_REQUEST";
export const TICKET_DETAILS_SUCCESS = "TICKET_DETAILS_SUCCESS";
export const TICKET_DETAILS_FAIL = "TICKET_DETAILS_FAIL";

export const STATICS_DETAILS_REQUEST = "STATICS_DETAILS_REQUEST";
export const STATICS_DETAILS_SUCCESS = "STATICS_DETAILS_SUCCESS";
export const STATICS_DETAILS_FAIL = "STATICS_DETAILS_FAIL";

export const TICKET_MINE_LIST_REQUEST = "TICKET_MINE_LIST_REQUEST";
export const TICKET_MINE_LIST_SUCCESS = "TICKET_MINE_LIST_SUCCESS";
export const TICKET_MINE_LIST_FAIL = "TICKET_MINE_LIST_FAIL";

export const TICKET_LIST_REQUEST = "TICKET_LIST_REQUEST";
export const TICKET_LIST_SUCCESS = "TICKET_LIST_SUCCESS";
export const TICKET_LIST_FAIL = "TICKET_LIST_FAIL";

export const TICKET_DELETE_REQUEST = "TICKET_DELETE_REQUEST";
export const TICKET_DELETE_SUCCESS = "TICKET_DELETE_SUCCESS";
export const TICKET_DELETE_FAIL = "TICKET_DELETE_FAIL";
export const TICKET_DELETE_RESET = "TICKET_DELETE_RESET";

export const TICKET_ANSWER_CREATE_REQUEST = "TICKET_ANSWER_CREATE_REQUEST";
export const TICKET_ANSWER_CREATE_SUCCESS = "TICKET_ANSWER_CREATE_SUCCESS";
export const TICKET_ANSWER_CREATE_FAIL = "TICKET_ANSWER_CREATE_FAIL";
export const TICKET_ANSWER_CREATE_RESET = "TICKET_ANSWER_CREATE_RESET";

export const EMAIL_TICKET_CREATE_REQUEST = "EMAIL_TICKET_CREATE_REQUEST";
export const EMAIL_TICKET_CREATE_SUCCESS = "EMAIL_TICKET_CREATE_SUCCESS";
export const EMAIL_TICKET_CREATE_FAIL = "EMAIL_TICKET_CREATE_FAIL";
export const EMAIL_TICKET_CREATE_RESET = "EMAIL_TICKET_CREATE_RESET";

export const EMAIL_TICKET_CREATE_REQUEST_ADMIN =
  "EMAIL_TICKET_CREATE_REQUEST_ADMIN";
export const EMAIL_TICKET_CREATE_SUCCESS_ADMIN =
  "EMAIL_TICKET_CREATE_SUCCESS_ADMIN";
export const EMAIL_TICKET_CREATE_FAIL_ADMIN = "EMAIL_TICKET_CREATE_FAIL_ADMIN";

export const EMAIL_TICKET_ANSWER_REQUEST = "EMAIL_TICKET_ANSWER_REQUEST";
export const EMAIL_TICKET_ANSWER_SUCCESS = "EMAIL_TICKET_ANSWER_SUCCESS";
export const EMAIL_TICKET_ANSWER_FAIL = "EMAIL_TICKET_ANSWER_FAIL";
export const EMAIL_TICKET_ANSWER_RESET = "EMAIL_TICKET_ANSWER_RESET";

export const EMAIL_TICKET_ANSWER_COMMENT_REQUEST =
  "EMAIL_TICKET_ANSWER_COMMENT_REQUEST";
export const EMAIL_TICKET_ANSWER_COMMENT_SUCCESS =
  "EMAIL_TICKET_ANSWER_COMMENT_SUCCESS";
export const EMAIL_TICKET_ANSWER_COMMENT_FAIL =
  "EMAIL_TICKET_ANSWER_COMMENT_FAIL";
